# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0002_actor_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='názov')),
                ('author', models.CharField(max_length=255, verbose_name='autor')),
                ('premiere_date', models.DateField(verbose_name='Dátum premiéry')),
                ('short_description', models.CharField(max_length=255, verbose_name='krátky popis')),
                ('full_description', models.TextField(verbose_name='dlhý popis')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('modification_time', models.DateTimeField(auto_now=True)),
                ('actors', models.ManyToManyField(blank=True, related_name='plays', to='actors.Actor', verbose_name='herci')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directed_shows', to='actors.Actor', verbose_name='režisér')),
            ],
            options={
                'verbose_name_plural': 'inscenácie',
                'ordering': ['-pk'],
                'verbose_name': 'inscenácia',
            },
        ),
    ]
