# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ['-pk'], 'verbose_name': 'Inscenácia', 'verbose_name_plural': 'Inscenácie'},
        ),
    ]
