# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0002_auto_20161008_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playcharacter',
            options={'verbose_name': 'Postava hry', 'verbose_name_plural': 'Postavy hry'},
        ),
        migrations.AlterField(
            model_name='playcharacter',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.Actor', verbose_name='herec'),
        ),
        migrations.AlterField(
            model_name='playcharacter',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plays.Play', verbose_name='hra'),
        ),
        migrations.AlterField(
            model_name='playimage',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='plays.Play', verbose_name='herec'),
        ),
    ]
