# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 15:47
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0002_auto_20160920_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='image_preview',
            field=django_resized.forms.ResizedImageField(blank=True, help_text='Fotka by mala mať veľkosť 650x418 pixelov. V opačnom prípade bude veľkosť zmenená automaticky.', upload_to='plays/previews', verbose_name='fotka pre náhľad'),
        ),
    ]
