# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0004_auto_20161015_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='full_description',
            field=tinymce.models.HTMLField(verbose_name='dlhý popis'),
        ),
        migrations.AlterField(
            model_name='play',
            name='image_preview',
            field=django_resized.forms.ResizedImageField(help_text='Fotka by mala mať veľkosť 650x418 pixelov. V opačnom prípade bude veľkosť zmenená automaticky.', upload_to='plays/previews', verbose_name='fotka pre náhľad'),
        ),
        migrations.AlterField(
            model_name='play',
            name='short_description',
            field=models.CharField(help_text='Použite najviac 170 znakov.', max_length=170, verbose_name='krátky popis'),
        ),
    ]
