# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 16:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plays', '0002_auto_20160920_1127'),
        ('actors', '0003_auto_20160920_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='názov')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('intro', models.CharField(max_length=255, verbose_name='výňatok')),
                ('body', models.TextField(verbose_name='obsah')),
                ('posted', models.DateTimeField(db_index=True, default=datetime.datetime(2016, 9, 20, 16, 53, 20, 267747, tzinfo=utc), verbose_name='čas pridania')),
                ('modification_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogposts', to='actors.Actor', verbose_name='autor')),
                ('related_play', models.ForeignKey(blank=True, help_text='Ak sa tento príspevok viaže k jednej z inscenácií, vyplňte toto pole', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogposts', to='plays.Play', verbose_name='pribuzná inscenácia')),
            ],
            options={
                'verbose_name_plural': 'Články',
                'verbose_name': 'Článok',
                'ordering': ['-posted'],
            },
        ),
    ]
