# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plays', '0002_auto_20160920_1127'),
        ('actors', '0003_auto_20160920_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='názov')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('intro', models.CharField(help_text='Použite úvodné 2-3 vety z článku.', max_length=255, verbose_name='výňatok')),
                ('body', tinymce.models.HTMLField(verbose_name='obsah')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='obrázok')),
                ('posted', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='čas pridania')),
                ('modification_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogposts', to='actors.Actor', verbose_name='autor')),
                ('related_play', models.ForeignKey(blank=True, help_text='Ak sa tento príspevok viaže k jednej z inscenácií, vyplňte toto pole', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogposts', to='plays.Play', verbose_name='pribuzná inscenácia')),
            ],
            options={
                'verbose_name_plural': 'Články',
                'verbose_name': 'Článok',
                'ordering': ['-posted'],
            },
        ),
    ]
