# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160920_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='intro',
            field=models.CharField(help_text='Použite úvodné 2-3 vety z článku.', max_length=255, verbose_name='výňatok'),
        ),
    ]
