# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 13:33
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255, verbose_name='miesto')),
                ('start_time', models.DateTimeField(verbose_name='čas začiatku')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='cena')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('modification_time', models.DateTimeField(auto_now=True)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='plays.Play', verbose_name='inscenácia')),
            ],
            options={
                'ordering': ['-start_time'],
                'verbose_name_plural': 'vystúpenia',
                'verbose_name': 'vystúpenie',
            },
        ),
    ]
