# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 09:09
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plays', '0002_auto_20160920_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(help_text='Napr. Empírove divadlo Hlohovec', max_length=255, verbose_name='miesto')),
                ('location_verbose', models.CharField(help_text='Napr. Empírove divadlo, Koperníkova 23, 920 01 Hlohovec', max_length=255, verbose_name='celá adresa')),
                ('description', models.CharField(help_text='Približne 2-3 vety, jedinečné pre každé predstavenie.', max_length=255, verbose_name='krátky popis')),
                ('start_time', models.DateTimeField(verbose_name='čas začiatku')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='cena')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('modification_time', models.DateTimeField(auto_now=True)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='plays.Play', verbose_name='inscenácia')),
            ],
            options={
                'verbose_name': 'Vystúpenie',
                'verbose_name_plural': 'Vystúpenia',
                'ordering': ['-start_time'],
            },
        ),
    ]
