# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['-start_time'], 'verbose_name': 'Vystúpenie', 'verbose_name_plural': 'Vystúpenia'},
        ),
    ]
