# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.CharField(help_text='Približne 2-3 vety, jedinečné pre každé predstavenie.', max_length=255, verbose_name='popis'),
        ),
    ]
