# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 22:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='používateľ')),
                ('bio', models.TextField(help_text='Popis herca.', verbose_name='biografia')),
                ('photo', models.ImageField(blank=True, help_text='Fotka by mala mať veľkosť 336x376 pixelov. V opačnom prípade bude veľkosť zmenená automaticky.', upload_to='actors/', verbose_name='fotka')),
            ],
            options={
                'ordering': ['-user'],
                'verbose_name': 'herec',
                'verbose_name_plural': 'herci',
            },
        ),
    ]
