# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 10:44
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_auto_20160920_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, help_text='Fotka by mala mať veľkosť 336x376 pixelov. V opačnom prípade bude veľkosť zmenená automaticky.', upload_to='actors/', verbose_name='fotka'),
        ),
    ]
