# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0005_auto_20161015_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.CharField(help_text=('Text výroku, ktorý sa zobrazí na úvodnej strane. Maximálna dĺžka je 200 znakov',), max_length=200, verbose_name='text'),
        ),
    ]
