# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 08:59
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0006_auto_20161015_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='bio',
            field=tinymce.models.HTMLField(help_text='Popis herca. Použite 300-400 znakov.', verbose_name='biografia'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=django_resized.forms.ResizedImageField(help_text='Fotka by mala mať veľkosť 336x376 pixelov. V opačnom prípade bude veľkosť zmenená automaticky.', upload_to='actors/', verbose_name='fotka'),
        ),
    ]
